
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/je/AppData/Local/Programs/Python/Python312/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
